### ISSUE TITLE
Catchable Fatal Error

### ISSUE THREAD

**Issue by 84pixels** [Stadkin/FixedDimensionsWatermarkResizer#1]
Hello,

How to implement on sonata_media conf?

My service :
- sonata.media.resizer.watermarkfixedDimensions:
- class: Application\Sonata\MediaBundle\Resizer\FixedDimensionsWatermarkResizer
- arguments: [@sonata.media.adapter.image.gd, 'outbound', @sonata.media.metadata.proxy]  

In my sonata_media : 
- thumbnail:   { width: 347, height: 190, quality: 100, constraint: false}
- resizer: sonata.media.resizer.watermarkfixedDimensions

Error :
Catchable Fatal Error: Argument 4 passed to Application\Sonata\MediaBundle\Resizer\FixedDimensionsWatermarkResizer::__construct() must implement interface Symfony\Component\DependencyInjection\ContainerInterface, none given.

Thanks for your help!

**Comment by Phoax** [comment]
Hello,

My service is: 
```
# sonata media watermark resizer
    sonata.media.resizer.watermarkfixeddimensions:
        class: Application\Sonata\MediaBundle\Resizer\FixedDimensionsWatermarkResizer
        arguments: [@sonata.media.adapter.image.gd, 'outbound', @sonata.media.metadata.proxy, @service_container, %copyright_file%]
```

I hope it helps,
